import type { Metadata } from "next";
import CheckLogin from "@/components/MyComponents/CheckLogin";
import {
  ClerkProvider,

} from '@clerk/nextjs'
import "./globals.css";
import DarkModeProvider from "@/components/MyComponents/DarkModeProvider";

export const metadata: Metadata = {
  title: "Eazify Cohort 2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <CheckLogin/>
          <DarkModeProvider/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
